protocol_version: 2.0.0
global_mode: RXTX
include_messages:
  IMU: { id: 1, mode: RXTX }
  FAKE_GPS: { id: 2, mode: RXTX }
  EXTERNAL_POSE: { id: 3, mode: RXTX }
  POS_SETPOINT: { id: 4, mode: RXTX }
  HIL_IN: { id: 5, mode: RXTX }
  HIL_OUT: { id: 6, mode: RXTX }
  VIO_POSE: { id: 7, mode: RXTX }
  KEYBOARD: { id: 8, mode: RXTX }